---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-test
  namespace: test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:sylvanasbeta/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image: stefanprodan/podinfo:dev-kdkxdr17
    replicaCount: 1
    hpa:
      enabled: false
